package com.homely.rental.notification.entity;

/**
 * Notification type enum.
 */
public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CONFIRMED,
    BOOKING_COMPLETED,
    BOOKING_CANCELLED,
    BOOKING_EXPIRED,
    VIEWING_REQUESTED,
    VIEWING_CONFIRMED,
    VIEWING_CANCELLED,
    VIEWING_COMPLETED,
    NEW_REVIEW,
    NEW_MESSAGE,
    REPORT_RESOLVED,
    LISTING_APPROVED,
    LISTING_REJECTED,
    LISTING_SUSPENDED,
    BOOKING_CASE_RESOLVED,
    USER_SUSPENDED,
    USER_RESTORED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_EXPIRED,
    PAYMENT_REFUNDED,
    SYSTEM_ANNOUNCEMENT
}
